# Nathan Tsai                                                                                                                                                                                                                                
# nwtsai@gmail.com                                                                                                                                                                                                                          
# 304575323                                                                                                                                                                                                                                   

lab1a: lab1a.c
	@gcc -o lab1a -g lab1a.c
clean:
	@rm -f lab1a *.tar.gz
dist:
	@tar -czf lab1a-304575323.tar.gz Makefile README lab1a.c
