# # # # # # # # # # # # # # # # # # # # #
# Nathan Tsai       # Regan Hsu         #
# nwtsai@gmail.com  # hsuregan@ucla.edu #
# 304575323         # 604296090         #
# # # # # # # # # # # # # # # # # # # # #

FLAGS = -Wall -Wextra -g

default:
	@cp lab3b.py lab3b
	@chmod +x lab3b
dist:
	@tar -czf lab3b-304575323.tar.gz lab3b.py Makefile README
clean:
	@rm -f *.tar.gz lab3b